# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem 'rest-client'
gem 'json'
gem 'pry'
gem 'sqlite3'
gem 'activerecord', "~>5.2.3"
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'